import{a as S,i as n,S as R}from"./assets/vendor-YT4DRQk6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const x="48935513-8997d7f633aa985d826258f4d",$="https://pixabay.com/api/",h=async(o,r,a)=>{try{return(await S.get($,{params:{key:x,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:a,page:r}})).data}catch(s){n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error(s)}},f=document.querySelector(".gallery"),O=()=>{f.innerHTML=""},y=o=>{const r=o.map(({webformatURL:s,largeImageURL:e,tags:t,likes:c,views:v,comments:w,downloads:q})=>`<a class="gallery-item" href="${e}">
          <div class="photo-card">
            <img src="${s}" alt="${t}" />
            <div class="info">
              <p><b>Likes:</b> ${c}</p>
              <p><b>Views:</b> ${v}</p>
              <p><b>Comments:</b> ${w}</p>
              <p><b>Downloads:</b> ${q}</p>
            </div>
          </div>
        </a>`).join("");f.insertAdjacentHTML("beforeend",r),new R(".gallery a").refresh()},g=document.querySelector("#search-form"),A=document.querySelector(".form-input"),b=document.querySelector(".loader"),m=document.querySelector(".load-more");let i=1,l="",p=0;const d=40,B=15;function L(){b.classList.add("active")}function u(){b.classList.remove("active")}function E(){m.style.display="block"}function P(){m.style.display="none"}g.addEventListener("submit",async o=>{if(o.preventDefault(),l=A.value.trim(),!l){n.warning({message:"Please enter a valid search query!",position:"topRight"});return}i=1,O(),L(),P();try{const r=await h(l,i,d),a=r.hits;if(u(),a.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),g.reset();return}y(a),g.reset(),p=r.totalHits,p>i*d&&E()}catch(r){u(),n.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),console.error(r)}});m.addEventListener("click",async()=>{i+=1,L();try{const o=Math.ceil(p/d),s=await h(l,i,i===o?B:d);u();const e=s.hits;y(e);const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),i>=o&&(P(),n.info({message:"We're sorry, but you've reached the end of search results",position:"topRight"}))}catch(o){u(),n.error({message:"An error occurred while loading more images.",position:"topRight"}),console.error(o)}});
//# sourceMappingURL=index.js.map
